import { NextResponse } from "next/server"
import type { Doctor } from "@/types"

const doctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    specialization: "Cardiology",
    profileImage: "/placeholder.svg?height=200&width=200&text=SJ",
    rating: 4.9,
    reviewCount: 127,
    location: "New York, NY",
    experience: 15,
    isAvailable: true,
    bio: "Dr. Sarah Johnson is a board-certified cardiologist with over 15 years of experience in treating cardiovascular diseases. She specializes in preventive cardiology and has published numerous research papers in leading medical journals.",
    qualifications: [
      "MD from Harvard Medical School",
      "Residency in Internal Medicine at Johns Hopkins",
      "Fellowship in Cardiology at Mayo Clinic",
      "Board Certified in Cardiovascular Disease",
    ],
    languages: ["English", "Spanish", "French"],
    consultationFee: 200,
    availableSlots: ["9:00 AM", "10:30 AM", "2:00 PM", "3:30 PM", "5:00 PM"],
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    specialization: "Dermatology",
    profileImage: "/placeholder.svg?height=200&width=200&text=MC",
    rating: 4.8,
    reviewCount: 89,
    location: "Los Angeles, CA",
    experience: 12,
    isAvailable: true,
    bio: "Dr. Michael Chen is a renowned dermatologist specializing in both medical and cosmetic dermatology. He has extensive experience in treating skin conditions and performing advanced dermatological procedures.",
    qualifications: [
      "MD from Stanford University School of Medicine",
      "Dermatology Residency at UCSF",
      "Fellowship in Mohs Surgery",
      "Board Certified in Dermatology",
    ],
    languages: ["English", "Mandarin", "Cantonese"],
    consultationFee: 180,
    availableSlots: ["8:30 AM", "11:00 AM", "1:30 PM", "4:00 PM"],
  },
  {
    id: "3",
    name: "Dr. Emily Rodriguez",
    specialization: "Pediatrics",
    profileImage: "/placeholder.svg?height=200&width=200&text=ER",
    rating: 4.9,
    reviewCount: 156,
    location: "Chicago, IL",
    experience: 10,
    isAvailable: false,
    bio: "Dr. Emily Rodriguez is a compassionate pediatrician dedicated to providing comprehensive healthcare for children from infancy through adolescence. She has a special interest in developmental pediatrics.",
    qualifications: [
      "MD from University of Chicago Pritzker School of Medicine",
      "Pediatrics Residency at Children's Hospital of Philadelphia",
      "Board Certified in Pediatrics",
      "Certificate in Developmental-Behavioral Pediatrics",
    ],
    languages: ["English", "Spanish"],
    consultationFee: 150,
    availableSlots: ["9:00 AM", "11:30 AM", "2:30 PM", "4:30 PM"],
  },
  {
    id: "4",
    name: "Dr. James Wilson",
    specialization: "Orthopedics",
    profileImage: "/placeholder.svg?height=200&width=200&text=JW",
    rating: 4.7,
    reviewCount: 98,
    location: "Houston, TX",
    experience: 18,
    isAvailable: true,
    bio: "Dr. James Wilson is an experienced orthopedic surgeon specializing in sports medicine and joint replacement. He has treated numerous professional athletes and is known for his innovative surgical techniques.",
    qualifications: [
      "MD from Baylor College of Medicine",
      "Orthopedic Surgery Residency at Hospital for Special Surgery",
      "Fellowship in Sports Medicine",
      "Board Certified in Orthopedic Surgery",
    ],
    languages: ["English"],
    consultationFee: 250,
    availableSlots: ["8:00 AM", "10:00 AM", "1:00 PM", "3:00 PM"],
  },
  {
    id: "5",
    name: "Dr. Lisa Thompson",
    specialization: "Neurology",
    profileImage: "/placeholder.svg?height=200&width=200&text=LT",
    rating: 4.8,
    reviewCount: 73,
    location: "Boston, MA",
    experience: 14,
    isAvailable: true,
    bio: "Dr. Lisa Thompson is a board-certified neurologist with expertise in treating neurological disorders including epilepsy, multiple sclerosis, and movement disorders. She is actively involved in clinical research.",
    qualifications: [
      "MD from Harvard Medical School",
      "Neurology Residency at Massachusetts General Hospital",
      "Fellowship in Epilepsy",
      "Board Certified in Neurology",
    ],
    languages: ["English", "German"],
    consultationFee: 220,
    availableSlots: ["9:30 AM", "12:00 PM", "2:30 PM", "4:30 PM"],
  },
  {
    id: "6",
    name: "Dr. Robert Kim",
    specialization: "Cardiology",
    profileImage: "/placeholder.svg?height=200&width=200&text=RK",
    rating: 4.9,
    reviewCount: 112,
    location: "Seattle, WA",
    experience: 16,
    isAvailable: true,
    bio: "Dr. Robert Kim is a leading interventional cardiologist with extensive experience in cardiac catheterization and angioplasty. He is known for his patient-centered approach and excellent outcomes.",
    qualifications: [
      "MD from University of Washington School of Medicine",
      "Internal Medicine Residency at UCSF",
      "Cardiology Fellowship at Cedars-Sinai",
      "Interventional Cardiology Fellowship",
    ],
    languages: ["English", "Korean"],
    consultationFee: 210,
    availableSlots: ["8:30 AM", "11:30 AM", "1:30 PM", "4:00 PM"],
  },
]

export async function GET() {
  return NextResponse.json(doctors)
}
